SELECT apt,city,country,created_at,id,id_from_source,sources_id,source_table,state,street,updated_at,zip  FROM dw_source.addresses
INSERT INTO dw_staging.addresses(apt,city,country,created_at,id,id_from_source,sources_id,source_table,state,street,updated_at,zip) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["apt"],row["city"],row["country"],row["created_at"],row["id"],row["id_from_source"],row["sources_id"],row["source_table"],row["state"],row["street"],row["updated_at"],row["zip"])
SELECT answerable_id,answerable_type,created_at,id,person_id,question_id,type,updated_at,value  FROM dw_source.answers
INSERT INTO dw_staging.answers(answerable_id,answerable_type,created_at,id,person_id,question_id,type,updated_at,value) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["answerable_id"],row["answerable_type"],row["created_at"],row["id"],row["person_id"],row["question_id"],row["type"],row["updated_at"],row["value"])
SELECT business_type,created_at,dln,encrypted_tax_id,fax,fiscal_year_end_date,id,id_from_source,name,no_of_employees,phone,sources_id,source_table,trade_name,updated_at  FROM dw_source.businesses
INSERT INTO dw_staging.businesses(business_type,created_at,dln,encrypted_tax_id,fax,fiscal_year_end_date,id,id_from_source,name,no_of_employees,phone,sources_id,source_table,trade_name,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["business_type"],row["created_at"],row["dln"],row["encrypted_tax_id"],row["fax"],row["fiscal_year_end_date"],row["id"],row["id_from_source"],row["name"],row["no_of_employees"],row["phone"],row["sources_id"],row["source_table"],row["trade_name"],row["updated_at"])
SELECT amount,business_score,business_type,created_at,decision,guarantors_20,id,lender_id,liquidity_ratio,liquid_credit_id,loan_id,max_amount,minimum_credit_score,mitigating_factor,product_id,request_type,risk_rating,risk_rating_data,risk_rating_v2,smart_rate,smart_rate_v2,updated_at  FROM dw_source.decisions
INSERT INTO dw_staging.decisions(amount,business_score,business_type,created_at,decision,guarantors_20,id,lender_id,liquidity_ratio,liquid_credit_id,loan_id,max_amount,minimum_credit_score,mitigating_factor,product_id,request_type,risk_rating,risk_rating_data,risk_rating_v2,smart_rate,smart_rate_v2,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["amount"],row["business_score"],row["business_type"],row["created_at"],row["decision"],row["guarantors_20"],row["id"],row["lender_id"],row["liquidity_ratio"],row["liquid_credit_id"],row["loan_id"],row["max_amount"],row["minimum_credit_score"],row["mitigating_factor"],row["product_id"],row["request_type"],row["risk_rating"],row["risk_rating_data"],row["risk_rating_v2"],row["smart_rate"],row["smart_rate_v2"],row["updated_at"])
SELECT app_number,created_at,id,loan_id,score,updated_at  FROM dw_source.etrans
INSERT INTO dw_staging.etrans(app_number,created_at,id,loan_id,score,updated_at) VALUES( '%s','%s','%s','%s','%s','%s') % (row["app_number"],row["created_at"],row["id"],row["loan_id"],row["score"],row["updated_at"])
SELECT average_balance_based_on,bank_account,business_id,confirmed,created_at,encrypted_account_number,fiscal_year_end_on,id,integration,last_tax_return_on,loan_id,open,personal_average_balance,routing_number,skip_bank_account,updated_at  FROM dw_source.financials
INSERT INTO dw_staging.financials(average_balance_based_on,bank_account,business_id,confirmed,created_at,encrypted_account_number,fiscal_year_end_on,id,integration,last_tax_return_on,loan_id,open,personal_average_balance,routing_number,skip_bank_account,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["average_balance_based_on"],row["bank_account"],row["business_id"],row["confirmed"],row["created_at"],row["encrypted_account_number"],row["fiscal_year_end_on"],row["id"],row["integration"],row["last_tax_return_on"],row["loan_id"],row["open"],row["personal_average_balance"],row["routing_number"],row["skip_bank_account"],row["updated_at"])
SELECT adjustable_id,adjustable_type,category,created_at,data,description,id,reason,type,updated_at  FROM dw_source.financial_adjustments
INSERT INTO dw_staging.financial_adjustments(adjustable_id,adjustable_type,category,created_at,data,description,id,reason,type,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["adjustable_id"],row["adjustable_type"],row["category"],row["created_at"],row["data"],row["description"],row["id"],row["reason"],row["type"],row["updated_at"])
SELECT business_property_rental_expense,cogs,created_at,depreciation_expense,financial_id,gross_sales,id,income_statement_from,income_statement_to,interest_expense,net_income,officers_compensation,total_expenses,updated_at  FROM dw_source.income_statements
INSERT INTO dw_staging.income_statements(business_property_rental_expense,cogs,created_at,depreciation_expense,financial_id,gross_sales,id,income_statement_from,income_statement_to,interest_expense,net_income,officers_compensation,total_expenses,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["business_property_rental_expense"],row["cogs"],row["created_at"],row["depreciation_expense"],row["financial_id"],row["gross_sales"],row["id"],row["income_statement_from"],row["income_statement_to"],row["interest_expense"],row["net_income"],row["officers_compensation"],row["total_expenses"],row["updated_at"])
SELECT code,created_at,eligible,id,parent_id,title,updated_at  FROM dw_source.industries
INSERT INTO dw_staging.industries(code,created_at,eligible,id,parent_id,title,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s') % (row["code"],row["created_at"],row["eligible"],row["id"],row["parent_id"],row["title"],row["updated_at"])
SELECT address_id,contact_fax,contact_first_name,contact_last_name,contact_phone,created_at,credit_score_provider,id,identifier,manual_max,manual_min,name,name_short,type,updated_at  FROM dw_source.lenders
INSERT INTO dw_staging.lenders(address_id,contact_fax,contact_first_name,contact_last_name,contact_phone,created_at,credit_score_provider,id,identifier,manual_max,manual_min,name,name_short,type,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["address_id"],row["contact_fax"],row["contact_first_name"],row["contact_last_name"],row["contact_phone"],row["created_at"],row["credit_score_provider"],row["id"],row["identifier"],row["manual_max"],row["manual_min"],row["name"],row["name_short"],row["type"],row["updated_at"])
SELECT copy,created_at,credit_issue,encrypted_json_response,encrypted_lender_json_response,id,lender_id,loan_id,mocked,public_record_issue,pull_type,submission_id,updated_at,version  FROM dw_source.liquid_credits
INSERT INTO dw_staging.liquid_credits(copy,created_at,credit_issue,encrypted_json_response,encrypted_lender_json_response,id,lender_id,loan_id,mocked,public_record_issue,pull_type,submission_id,updated_at,version) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["copy"],row["created_at"],row["credit_issue"],row["encrypted_json_response"],row["encrypted_lender_json_response"],row["id"],row["lender_id"],row["loan_id"],row["mocked"],row["public_record_issue"],row["pull_type"],row["submission_id"],row["updated_at"],row["version"])
SELECT active_items,admin_id,agency,amount,amount_requested,api_assisted,assigned_date,assignment_read_at,campaign_id,created_at,external_member_status,fees,fees_hash,handed_off_at,id,intended_use_of_funds,interest_rate,interest_rate_with_fees,last_statistic_created_at,lead_id,lender_id,max_loan_amount_clean,medium,monthly_payment,partner_customer_id,partner_id,partner_referral_pct,person_id,position,previous_state,prime_rate,priority,product_id,promotion_id,promo_code,recommended_apply_date,reengagement,referred_by_id,sales_assisted,sales_assisted_denied_at,sales_assisted_requested_at,smart_rate,source,state,term,updated_at  FROM dw_source.loans
INSERT INTO dw_staging.loans(active_items,admin_id,agency,amount,amount_requested,api_assisted,assigned_date,assignment_read_at,campaign_id,created_at,external_member_status,fees,fees_hash,handed_off_at,id,intended_use_of_funds,interest_rate,interest_rate_with_fees,last_statistic_created_at,lead_id,lender_id,max_loan_amount_clean,medium,monthly_payment,partner_customer_id,partner_id,partner_referral_pct,person_id,position,previous_state,prime_rate,priority,product_id,promotion_id,promo_code,recommended_apply_date,reengagement,referred_by_id,sales_assisted,sales_assisted_denied_at,sales_assisted_requested_at,smart_rate,source,state,term,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["active_items"],row["admin_id"],row["agency"],row["amount"],row["amount_requested"],row["api_assisted"],row["assigned_date"],row["assignment_read_at"],row["campaign_id"],row["created_at"],row["external_member_status"],row["fees"],row["fees_hash"],row["handed_off_at"],row["id"],row["intended_use_of_funds"],row["interest_rate"],row["interest_rate_with_fees"],row["last_statistic_created_at"],row["lead_id"],row["lender_id"],row["max_loan_amount_clean"],row["medium"],row["monthly_payment"],row["partner_customer_id"],row["partner_id"],row["partner_referral_pct"],row["person_id"],row["position"],row["previous_state"],row["prime_rate"],row["priority"],row["product_id"],row["promotion_id"],row["promo_code"],row["recommended_apply_date"],row["reengagement"],row["referred_by_id"],row["sales_assisted"],row["sales_assisted_denied_at"],row["sales_assisted_requested_at"],row["smart_rate"],row["source"],row["state"],row["term"],row["updated_at"])
SELECT created_at,id,loan_id,reason_id,updated_at  FROM dw_source.loans_reasons
INSERT INTO dw_staging.loans_reasons(created_at,id,loan_id,reason_id,updated_at) VALUES( '%s','%s','%s','%s','%s') % (row["created_at"],row["id"],row["loan_id"],row["reason_id"],row["updated_at"])
SELECT business_id,id,loan_id  FROM dw_source.loan_business_info
INSERT INTO dw_staging.loan_business_info(business_id,id,loan_id) VALUES( '%s','%s','%s') % (row["business_id"],row["id"],row["loan_id"])
SELECT aggregator_partner,created_at,display_name,id,lender_id,loan_term,min_smart_rate,name,owner_id,partner_assisted,prepayment_penalty,primary_type,referral_pct,smartrate,special_partner,state_updated_at,updated_at  FROM dw_source.partners
INSERT INTO dw_staging.partners(aggregator_partner,created_at,display_name,id,lender_id,loan_term,min_smart_rate,name,owner_id,partner_assisted,prepayment_penalty,primary_type,referral_pct,smartrate,special_partner,state_updated_at,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["aggregator_partner"],row["created_at"],row["display_name"],row["id"],row["lender_id"],row["loan_term"],row["min_smart_rate"],row["name"],row["owner_id"],row["partner_assisted"],row["prepayment_penalty"],row["primary_type"],row["referral_pct"],row["smartrate"],row["special_partner"],row["state_updated_at"],row["updated_at"])
SELECT admin,citizenship,created_at,DOB,email,fax,first_name,gender,id,id_from_source,last_name,middle_name,mobile_phone,person_type,phone,sources_id,source_table,updated_at  FROM dw_source.persons
INSERT INTO dw_staging.persons(admin,citizenship,created_at,DOB,email,fax,first_name,gender,id,id_from_source,last_name,middle_name,mobile_phone,person_type,phone,sources_id,source_table,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["admin"],row["citizenship"],row["created_at"],row["DOB"],row["email"],row["fax"],row["first_name"],row["gender"],row["id"],row["id_from_source"],row["last_name"],row["middle_name"],row["mobile_phone"],row["person_type"],row["phone"],row["sources_id"],row["source_table"],row["updated_at"])
SELECT addressable_type,address_type,business_person_id,id  FROM dw_source.person_business_addresses
INSERT INTO dw_staging.person_business_addresses(addressable_type,address_type,business_person_id,id) VALUES( '%s','%s','%s','%s') % (row["addressable_type"],row["address_type"],row["business_person_id"],row["id"])
SELECT category,created_at,id,info,lender_id,name,updated_at  FROM dw_source.products
INSERT INTO dw_staging.products(category,created_at,id,info,lender_id,name,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s') % (row["category"],row["created_at"],row["id"],row["info"],row["lender_id"],row["name"],row["updated_at"])
SELECT active,created_at,default,description,ends_at,id,lender_id,name,partner_id,starts_at,updated_at  FROM dw_source.promotions
INSERT INTO dw_staging.promotions(active,created_at,default,description,ends_at,id,lender_id,name,partner_id,starts_at,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["active"],row["created_at"],row["default"],row["description"],row["ends_at"],row["id"],row["lender_id"],row["name"],row["partner_id"],row["starts_at"],row["updated_at"])
SELECT active,created_at,description,format,id,number,parent_answer,parent_id,required_answer,section,updated_at  FROM dw_source.questions
INSERT INTO dw_staging.questions(active,created_at,description,format,id,number,parent_answer,parent_id,required_answer,section,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s') % (row["active"],row["created_at"],row["description"],row["format"],row["id"],row["number"],row["parent_answer"],row["parent_id"],row["required_answer"],row["section"],row["updated_at"])
SELECT code,created_at,description,id,manual,type,updated_at  FROM dw_source.reasons
INSERT INTO dw_staging.reasons(code,created_at,description,id,manual,type,updated_at) VALUES( '%s','%s','%s','%s','%s','%s','%s') % (row["code"],row["created_at"],row["description"],row["id"],row["manual"],row["type"],row["updated_at"])
SELECT active,created_at,id,name,updated_at  FROM dw_source.sources
INSERT INTO dw_staging.sources(active,created_at,id,name,updated_at) VALUES( '%s','%s','%s','%s','%s') % (row["active"],row["created_at"],row["id"],row["name"],row["updated_at"])
SELECT created_at,id,lender_id,loan_id,state,updated_at  FROM dw_source.statistics
INSERT INTO dw_staging.statistics(created_at,id,lender_id,loan_id,state,updated_at) VALUES( '%s','%s','%s','%s','%s','%s') % (row["created_at"],row["id"],row["lender_id"],row["loan_id"],row["state"],row["updated_at"])
SELECT id,item,item_type,needed_for_dw  FROM dw_source.tax_items
INSERT INTO dw_staging.tax_items(id,item,item_type,needed_for_dw) VALUES( '%s','%s','%s','%s') % (row["id"],row["item"],row["item_type"],row["needed_for_dw"])
SELECT business_id,co_social_bp_id,filing_status,form_type,id,processing_date,social_bp_Id,year  FROM dw_source.tax_returns
INSERT INTO dw_staging.tax_returns(business_id,co_social_bp_id,filing_status,form_type,id,processing_date,social_bp_Id,year) VALUES( '%s','%s','%s','%s','%s','%s','%s','%s') % (row["business_id"],row["co_social_bp_id"],row["filing_status"],row["form_type"],row["id"],row["processing_date"],row["social_bp_Id"],row["year"])
SELECT id,item_value,tax_item_id,tax_returns_id  FROM dw_source.tax_return_items
INSERT INTO dw_staging.tax_return_items(id,item_value,tax_item_id,tax_returns_id) VALUES( '%s','%s','%s','%s') % (row["id"],row["item_value"],row["tax_item_id"],row["tax_returns_id"])
